[package]
name = "rust_starter_project"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "*"

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "bin"
path = "src/main.rs"

[[bench]]
name = "bench"
harness = false
